# Generated by Django 5.2.6 on 2025-09-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_kategori_nama_kategori_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('IN', 'pemasukan'), ('OUT', 'pengeluaran')])),
                ('jumlah', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kategori')),
            ],
        ),
    ]
